import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../../comman/Colors';
import FontsSize from '../../../../comman/Sizes/FontsSize';
import MarginHW from '../../../../comman/Sizes/MarginHW';
import fonts from '../../../../comman/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.screenGray,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingVertical: MarginHW.PaddingH14,
  },
  headerIcon: {
    fontSize: FontsSize.size22,
    color: Colors.brandBlue,
    fontFamily: fonts.Lexend_Regular,
  },
  headerTitle: {
    fontSize: FontsSize.size18,
    fontFamily: fonts.LexendBold,
    color: Colors.brandBlue,
  },
  headerHelp: {
    fontSize: FontsSize.size18,
    color: Colors.brandBlue,
    fontFamily: fonts.LexendBold,
  },
  helpContainer: {
    width: MarginHW.MarginW24,
    height: MarginHW.MarginW24,
    borderRadius: MarginHW.MarginW12,
    backgroundColor: Colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpText: {
    color: Colors.white,
    fontSize: FontsSize.size14,
    fontFamily: fonts.LexendBold,
  },
  scrollContent: {
    paddingBottom: MarginHW.MarginH100,
  },
  bannerContainer: {
    marginHorizontal: MarginHW.MarginW20,
    marginTop: MarginHW.MarginH10,
    backgroundColor: Colors.brandBlue,
    borderRadius: 20,
    padding: MarginHW.PaddingW24,
    overflow: 'hidden',
    shadowColor: Colors.brandBlue,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  bannerPattern1: {
    position: 'absolute',
    top: -50,
    right: -20,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: Colors.white10,
  },
  bannerPattern2: {
    position: 'absolute',
    bottom: -80,
    left: -40,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: Colors.white10,
  },
  upgradePill: {
    backgroundColor: Colors.white18,
    paddingHorizontal: MarginHW.PaddingW12,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  upgradePillText: {
    color: Colors.white,
    fontSize: FontsSize.size12,
    fontFamily: fonts.Lexend_Medium,
    letterSpacing: 1,
  },
  bannerTitle: {
    color: Colors.white,
    fontSize: FontsSize.size20,
    fontFamily: fonts.Lexend_ExtraBold,
    marginVertical: MarginHW.MarginH8,
  },
  bannerDesc: {
    color: Colors.white85,
    fontSize: FontsSize.size12,
    lineHeight: 22,
    maxWidth: '85%',
    fontFamily: fonts.Lexend_Regular,
  },
  sectionTitle: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.LexendBold,
    color: Colors.mutedSlate,
    letterSpacing: 1,
    marginTop: MarginHW.MarginH30,
    marginBottom: MarginHW.MarginH14,
    marginHorizontal: MarginHW.MarginW20,
  },
  advantageCard: {
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW20,
    marginBottom: MarginHW.MarginH14,
    borderRadius: 16,
    padding: MarginHW.PaddingW20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  advIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: Colors.badgeBlueTint,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW16,
  },
  advIcon: {
    width: 24,
    height: 24,
      tintColor: Colors.brandBlue,
  },
  advIconText: {
    fontSize: FontsSize.size22,
    fontFamily: fonts.Lexend_Regular,
  },
  advTextContainer: {
    flex: 1,
  },
  advTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.LexendBold,
    color: Colors.titleInk,
    marginBottom: MarginHW.MarginH4,
  },
  advDesc: {
    fontSize: FontsSize.size12,
    color: Colors.mutedSlate,
    lineHeight: 18,
    fontFamily: fonts.Lexend_Regular,
  },
  planCard: {
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW20,
    marginBottom: MarginHW.MarginH14,
    borderRadius: 16,
    padding: MarginHW.PaddingW20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.dotInactive,
  },
  planCardActive: {
    borderColor: Colors.brandBlue,
    backgroundColor: Colors.screenGray,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.dotInactive,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW16,
  },
  radioOuterActive: {
    borderColor: Colors.brandBlue,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.brandBlue,
  },
  planTextContainer: {
    flex: 1,
  },
  planTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.LexendBold,
    color: Colors.titleInk,
    marginBottom: MarginHW.MarginH4,
  },
  planDesc: {
    fontSize: FontsSize.size12,
    color: Colors.mutedSlate,
    fontFamily: fonts.Lexend_Regular,
  },
  planPriceContainer: {
    alignItems: 'flex-end',
  },
  planPrice: {
    fontSize: FontsSize.size20,
    fontFamily: fonts.Lexend_ExtraBold,
    color: Colors.brandBlue,
  },
  planPeriod: {
    fontSize: FontsSize.size12,
    color: Colors.mutedSlate,
    fontFamily: fonts.Lexend_Medium,
  },
  originalPrice: {
    fontSize: FontsSize.size12,
    color: Colors.mutedSlate,
    textDecorationLine: 'line-through',
    marginTop: MarginHW.MarginH2,
    fontFamily: fonts.Lexend_Regular,
  },
  bestValueTag: {
    position: 'absolute',
    top: -12,
    right: 20,
    backgroundColor: '#8B4513',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH3,
    borderRadius: 4,
  },
  bestValueText: {
    color: Colors.white,
    fontSize: FontsSize.size10,
    fontFamily: fonts.LexendBold,
    letterSpacing: 0.5,
  },
  testimonialContainer: {
    marginHorizontal: MarginHW.MarginW20,
    marginTop: MarginHW.MarginH14,
    marginBottom: MarginHW.MarginH30,
    height: 160,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: Colors.cardGray,
    justifyContent: 'flex-end',
    padding: MarginHW.PaddingW20,
  },
  testimonialOverlay: {
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  testimonialText: {
    fontSize: FontsSize.size14,
    fontStyle: 'italic',
    color: Colors.bodyGray,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: MarginHW.MarginH10,
    fontFamily: fonts.Lexend_Regular,
  },
  testimonialAuthor: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.LexendBold,
    color: Colors.brandBlue,
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.screenGray,
    paddingHorizontal: MarginHW.PaddingW20,
    paddingTop: MarginHW.PaddingH14,
    paddingBottom: Platform.OS === 'ios' ? MarginHW.PaddingH30 : MarginHW.PaddingH20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
  },
  upgradeButton: {
    backgroundColor: Colors.brandBlue,
    borderRadius: 12,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.brandBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  upgradeButtonText: {
    color: Colors.white,
    fontSize: FontsSize.size16,
    fontFamily: fonts.LexendBold,
    marginRight: MarginHW.MarginW8,
  },
  secureText: {
    textAlign: 'center',
    fontSize: FontsSize.size10,
    color: Colors.mutedSlate,
    marginTop: MarginHW.MarginH12,
    fontFamily: fonts.Lexend_Regular,
  }
});