import { StyleSheet } from "react-native";
import Colors from "../../../../comman/Colors";
import HWSize from "../../../../comman/Sizes/HWSize";
import FontsSize from "../../../../comman/Sizes/FontsSize";
import fonts from "../../../../comman/fonts";
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.offWhite,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: hp(0.5),
        paddingHorizontal: wp(5),
        backgroundColor: Colors.white,
    },
    headerTitle: {
        fontSize: FontsSize.size20,
        fontFamily: fonts.LexendBold,
        color: Colors.heroNavy,
    },
    scrollContent: {
        paddingBottom: hp(5),
    },
    profileSection: {
        alignItems: 'center',
        paddingTop: hp(1.5),
    },
    avatarContainer: {
        position: 'relative',
    },
    avatar: {
        width: wp(20),
        height: wp(20),
        borderRadius: wp(10),
        backgroundColor: Colors.iceBlue,
    },
    editIconContainer: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: Colors.primaryBlue,
        width: wp(8),
        height: wp(8),
        borderRadius: wp(4),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: Colors.white,
    },
    userName: {
        fontSize: FontsSize.size20,
        fontFamily: fonts.LexendBold,
        color: Colors.titleInk,
        marginTop: hp(1),
    },
    userRole: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.Lexend_Medium,
        color: Colors.mutedSlate,
        marginTop: hp(0.5),
    },
    userLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: hp(0.5),
    },
    locationText: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.Lexend_Regular,
        color: Colors.mutedSlate,
        marginLeft: wp(1),
    },
    editProfileButton: {
        marginTop: hp(1),
        backgroundColor: Colors.cardGray,
        paddingHorizontal: wp(8),
        paddingVertical: hp(1.2),
        borderRadius: wp(2),
    },
    editProfileText: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.Lexend_SemiBold,
        color: Colors.primaryBlue,
    },
    strengthCard: {
        backgroundColor: Colors.primaryBlue,
        marginHorizontal: wp(5),
        marginTop: hp(2),
        borderRadius: wp(5),
        padding: wp(5),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        elevation: 5,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    strengthLeft: {
        flex: 1,
    },
    strengthTitle: {
        fontSize: FontsSize.size18,
        fontFamily: fonts.LexendBold,
        color: Colors.white,
    },
    strengthDesc: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.Lexend_Regular,
        color: Colors.white85,
        marginTop: hp(1),
        lineHeight: hp(2),
    },
    completeNowButton: {
        backgroundColor: Colors.white,
        paddingHorizontal: wp(4),
        paddingVertical: hp(0.8),
        borderRadius: wp(2),
        marginTop: hp(2),
        alignSelf: 'flex-start',
    },
    completeNowText: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.Lexend_SemiBold,
        color: Colors.primaryBlue,
    },
    progressContainer: {
        width: wp(20),
        height: wp(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressCircle: {
        width: wp(18),
        height: wp(18),
        borderRadius: wp(9),
        borderWidth: wp(1.5),
        borderColor: Colors.white18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressText: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.LexendBold,
        color: Colors.white,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: wp(5),
        marginTop: hp(3),
    },
    sectionTitle: {
        fontSize: FontsSize.size18,
        fontFamily: fonts.LexendBold,
        color: Colors.titleInk,
        marginLeft: wp(2),
    },
    tipsContainer: {
        flexDirection: 'row',
        marginHorizontal: wp(5),
        marginTop: hp(1.5),
        justifyContent: 'space-between',
    },
    tipCard: {
        width: wp(43),
        backgroundColor: Colors.iceBlue,
        padding: wp(4),
        borderRadius: wp(4),
        justifyContent: 'space-between',
    },
    tipIconContainer: {
        backgroundColor: Colors.white,
        width: wp(10),
        height: wp(10),
        borderRadius: wp(2),
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: hp(1.5),
    },
    tipText: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.Lexend_Medium,
        color: Colors.heroNavy,
        lineHeight: hp(2),
    },
    tipBadge: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.LexendBold,
        color: Colors.primaryBlue,
        marginTop: hp(1),
    },
    tipVerifyAction: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.LexendBold,
        color: Colors.mutedSlate,
        marginTop: hp(1),
    },
    statsContainer: {
        flexDirection: 'row',
        marginHorizontal: wp(5),
        marginTop: hp(2),
        justifyContent: 'space-between',
    },
    statCard: {
        width: wp(43),
        backgroundColor: Colors.white,
        padding: wp(5),
        borderRadius: wp(4),
        alignItems: 'flex-start',
        elevation: 2,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    statNumber: {
        fontSize: FontsSize.size28,
        fontFamily: fonts.LexendBold,
        color: Colors.primaryBlue,
    },
    statLabel: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.LexendBold,
        color: Colors.mutedSlate,
        marginTop: hp(0.5),
    },
    resumeSectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginHorizontal: wp(5),
        marginTop: hp(3),
    },
    resumeTitle: {
        fontSize: FontsSize.size18,
        fontFamily: fonts.LexendBold,
        color: Colors.titleInk,
    },
    uploadNewText: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.Lexend_SemiBold,
        color: Colors.primaryBlue,
    },
    resumeCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.white,
        marginHorizontal: wp(5),
        marginTop: hp(1.5),
        padding: wp(4),
        borderRadius: wp(4),
        elevation: 2,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    pdfIconContainer: {
        width: wp(12),
        height: wp(12),
        backgroundColor: Colors.lightRed,
        borderRadius: wp(2),
        justifyContent: 'center',
        alignItems: 'center',
    },
    resumeInfo: {
        flex: 1,
        marginLeft: wp(4),
    },
    resumeName: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.LexendBold,
        color: Colors.cardTitle,
    },
    resumeMeta: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.Lexend_Regular,
        color: Colors.mutedSlate,
        marginTop: hp(0.3),
    },
    experienceCard: {
        backgroundColor: Colors.white,
        marginHorizontal: wp(5),
        marginTop: hp(1.5),
        padding: wp(4),
        borderRadius: wp(4),
        flexDirection: 'row',
    },
    experienceCard1: {
        backgroundColor: Colors.white,
        marginHorizontal: wp(5),
        marginTop: hp(1.5),
        marginBottom: hp(6),
        padding: wp(4),
        borderRadius: wp(4),
        flexDirection: 'row',
    },
    experienceIcon: {
        width: wp(12),
        height: wp(12),
        backgroundColor: Colors.cardGray,
        borderRadius: wp(2),
        justifyContent: 'center',
        alignItems: 'center',
    },
    experienceContent: {
        flex: 1,
        marginLeft: wp(4),
    },
    expRole: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.LexendBold,
        color: Colors.cardTitle,
    },
    expCompany: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.Lexend_Medium,
        color: Colors.mutedSlate,
        marginTop: hp(0.3),
    },
    expDate: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.Lexend_Regular,
        color: Colors.mutedSlate,
        marginTop: hp(0.3),
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginHorizontal: wp(5),
        marginTop: hp(1.5),
    },
    editIcon: {
        fontSize: wp(3),
        color: Colors.primaryBlue,
    }
});

export default styles;