import { StyleSheet } from 'react-native';
import Colors from '../../../../comman/Colors';
import FontsSize from '../../../../comman/Sizes/FontsSize';
import MarginHW from '../../../../comman/Sizes/MarginHW';
import fonts from '../../../../comman/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW16,
  },
  scrollContent: {
   
  },
  jobBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.aliceBlue,
    padding: MarginHW.MarginH16,
    borderRadius: 16,
    marginTop: MarginHW.MarginH5,
    borderWidth: 1,
    borderColor: Colors.softBlue,
  },
  jobIconBox: {
   
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW16,
  },
  jobIcon: {
    width: MarginHW.MarginW40,
    height: MarginHW.MarginW40,
    resizeMode: 'contain',
  },
  applyingForText: {
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.size10,
    color: Colors.mutedSlate,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  jobTitleText: {
    fontFamily: fonts.LexendBold,
    fontSize: FontsSize.size16,
    color: Colors.brandBlue,
    marginTop: MarginHW.MarginH2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: MarginHW.MarginH16,
  
  },
  sectionTitle: {
    fontFamily: fonts.LexendBold,
    fontSize: FontsSize.size14,
    color: Colors.inkDark,
    letterSpacing: 0.2,
  },
  editInfoText: {
    fontFamily: fonts.Lexend_Medium,
    fontSize: FontsSize.size12,
    color: Colors.primaryBlue,
  },
  infoCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: MarginHW.MarginH16,
    marginBottom: MarginHW.MarginH12,
    borderWidth: 1,
    borderColor: Colors.lightGray,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  infoLabel: {
    fontFamily: fonts.LexendBold,
    fontSize: FontsSize.size10,
    color: Colors.mutedSlate,
    textTransform: 'uppercase',
    marginBottom: MarginHW.MarginH4,
  },
  infoValue: {
    fontFamily: fonts.Lexend_Medium,
    fontSize: FontsSize.size14,
    color: Colors.inkDark,
  },
  infoInput: {
    fontFamily: fonts.Lexend_Medium,
    fontSize: FontsSize.size14,
    color: Colors.inkDark,
    padding: 0,
    minHeight: MarginHW.MarginH24,
  },
  resumeCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: MarginHW.MarginH16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH24,
    borderWidth: 1,
    borderColor: Colors.lightGray,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  resumeIconBox: {
    width: MarginHW.MarginW45,
    height: MarginHW.MarginW45,
    backgroundColor: Colors.lightRed,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  resumeIcon: {
    width: MarginHW.MarginW20,
    height: MarginHW.MarginW20,
    tintColor: Colors.errorRed,
    resizeMode: 'contain',
  },
  resumeDetails: {
    flex: 1,
  },
  resumeName: {
    fontFamily: fonts.LexendBold,
    fontSize: FontsSize.size14,
    color: Colors.inkDark,
  },
  resumeMeta: {
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.normalize12,
    color: Colors.mutedSlate,
    marginTop: MarginHW.MarginH2,
  },
  eyeIcon: {
    width: MarginHW.MarginW18,
    height: MarginHW.MarginW18,
    tintColor: Colors.mutedSlate,
    marginRight: MarginHW.MarginW12,
  },
  changeButton: {
    backgroundColor: Colors.aliceBlue,
    paddingHorizontal: MarginHW.MarginW10,
    paddingVertical: MarginHW.MarginH5,
    borderRadius: 6,
  },
  changeButtonText: {
    fontFamily: fonts.Lexend_Medium,
    fontSize: FontsSize.size10,
    color: Colors.primaryBlue,
  },
  charCountText: {
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.size10,
    color: Colors.mutedSlate,
  },
  coverLetterInputContainer: {
    backgroundColor: Colors.offWhite,
    borderRadius: 12,
    padding: MarginHW.MarginH16,
    height: MarginHW.MarginH100 + MarginHW.MarginH60,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  coverLetterInput: {
    flex: 1,
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.size14,
    color: Colors.inkDark,
    textAlignVertical: 'top',
    padding: 0,
  },
  charCountFooter: {
    alignItems: 'flex-end',
    marginTop: MarginHW.MarginH4,
  },
  footerText: {
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.normalize12,
    color: Colors.mutedSlate,
  },
  toastContainer: {
    backgroundColor: Colors.inkDark,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: MarginHW.MarginH12,
    paddingHorizontal: MarginHW.MarginW16,
    borderRadius: 10,
    marginBottom: MarginHW.MarginH16,
    marginHorizontal: MarginHW.MarginW16,
  },
  toastIcon: {
    width: MarginHW.MarginW20,
    height: MarginHW.MarginW20,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW8,
  },
  toastText: {
    fontFamily: fonts.Lexend_Medium,
    fontSize: FontsSize.normalize14,
    color: Colors.white,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: MarginHW.MarginH20,
    paddingBottom: MarginHW.MarginH35,
    paddingHorizontal: MarginHW.MarginW20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 20,
  },
  submitButton: {
    backgroundColor: Colors.primaryBlue,
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: MarginHW.MarginH18,
    marginBottom: MarginHW.MarginH12,
    shadowColor: Colors.primaryBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  submitButtonText: {
    fontFamily: fonts.LexendBold,
    fontSize: FontsSize.size16,
    color: Colors.white,
    marginRight: MarginHW.MarginW8,
  },
  submitIcon: {
    width: MarginHW.MarginW18,
    height: MarginHW.MarginW18,
    tintColor: Colors.white,
    resizeMode: 'contain',
  },
  termsText: {
    fontFamily: fonts.Lexend_Regular,
    fontSize: FontsSize.size10,
    color: Colors.mutedSlate,
    textAlign: 'center',
    lineHeight: 16,
  },
  termsLink: {
    fontFamily: fonts.Lexend_Medium,
    color: Colors.inkDark,
  }
});

export default styles;