import Images from "./Images";

export const APP_TEXT = {
  appName: 'AcademicArchitect',
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Continue your journey toward professional excellence with your AI-powered career assistant.',
  CareerArchitect: 'Career Architect',
  splashSubtitle: 'Find Govt & Private Jobs in One Place',
  splashAuthStatus: 'AUTHENTICATING ENVIRONMENT',
  splashVersionInfo: 'v4.0.2 - Secure Institutional Access',
  loginButton: 'Send OTP',
  loginButtonGoogle: 'Continue with Google',
  loginButtonSecure: 'SECURE LOGIN',
  loginButtonContinue: 'Continue',
  loginButtonSkip: 'Skip',
  loginButtonNext: 'Next',
  loginButtonGetStarted: 'Get Started',
  loginButtonLogin: 'Login',
  loginButtonRegister: 'Register',
  loginButtonForgotPassword: 'Forgot Password',
  loginButtonResetPassword: 'Reset Password',
  loginButtonVerify: 'Verify',
  loginSectionLabelMobileNumber: 'MOBILE NUMBER',
  loginOrContinueWith: 'OR CONTINUE WITH',
  loginNewToAppName: 'New to AcademicArchitect',
  loginJoinTheCollective: 'Join the collective',
  otpHeader: 'Verification',
  otpTitle: 'Verify Your Number',
  otpSubtitlePrefix: "We've sent a 6-digit code to",
  otpPhoneNumber: '98765 43210',
  otpVerifyButton: 'Verify & Proceed',
  otpResendPrefix: 'Resend Code in',
  otpResendTime: '00:30',
  otpChangePhoneNumber: 'Change Phone Number',
  otpFooter: 'SECURE 256-BIT ENCRYPTED VERIFICATION',
  signupTitle: 'Join the Collective',
  signupSubtitle: 'Start your professional journey with AI-powered matches.',
  signupFullNameLabel: 'Full Name',
  signupMobileLabel: 'Mobile Number',
  signupFullNamePlaceholder: 'Enter Your Name',
  signupMobilePlaceholder: 'Enter Your Mobile Number',
  signupButton: 'Join Now',
  signupOrText: 'OR',
  signupGoogleButton: 'Sign up with Google',
  signupAlreadyAccount: 'Already have an account?',
  signupLoginAction: 'Login',
  homeHeaderTitle: 'Academic Architect',
  homeSearchPlaceholder: 'Search jobs, exams, or companies',
  homeFindNow: 'Find Now',
  homeNewJobsBadge: 'NEW JOBS',
  homeNewJobsTitle: '36 New jobs match your profile perfectly today.',
  homeNewJobsMatches: 'View All Matches',
  homeQuickViewLabel: 'QUICK VIEW',
  homeQuickViewTitle: 'Exam Results',
  homeDownloadLabel: 'DOWNLOAD',
  homeDownloadTitle: 'Admit Cards',
  homeRecommendedTitle: 'Recommended for You',
  homeSeeAll: 'See all',
  homeQuickApply: 'Quick Apply',
  homeLatestGovtJobsTitle: 'Latest Govt Jobs',
  homeGovtSectionIcon: '🏛',
  homeGovtDepartment: 'Dept. of Personnel & Training',
  homeDeadlineLabel: 'DEADLINE',
  homePrivateSectorTitle: 'Private Sector',
  homePrivateSectionIcon: '🏢',
  homeUpcomingExamTitle: 'Upcoming Exam Notifications',
  homeFullSchedule: 'Full Schedule',
  homeCalendarIcon: '📅',
  homeDetailsArrow: 'Details →',
  homeQuickViewIcon: '📋',
  homeDownloadIcon: '📥',
  homeCompanyIcon: '🏢',
  homeCuratedBy: 'Curated by Academic Architect AI',
  jobsHeaderTitle: 'Indus Pro',
  jobsHeaderSearchIcon: '⌕',
  jobsSearchIcon: '⌕',
  jobsSearchPlaceholder: 'Search jobs, roles, or comp',
  jobsFilterIcon: '',
  jobsFilterLocation: 'Location',
  jobsFilterExperience: 'Experience',
  jobsFilterType: 'Job Type',
  jobsFilterSalary: 'Salary',
  jobsRecommendedTitle: 'RECOMMENDED FOR YOU',
  jobsLocationIcon: '📍',
  jobsSalaryIcon: '💸',
  prepTitle: 'Boost Your Preparation',
  examFilters: ['Govt Jobs', 'Results', 'Admit Cards', ],
  examSearchPlaceholder: 'Search for exam notifications, updates',
  examLatestAnnouncements: 'LATEST ANNOUNCEMENTS',
  examRecentNotifications: 'Recent Notifications',
  examViewHistory: 'View History',
  examSyllabusUpdate: 'RRB NTPC Syllabus Update',
  examSyllabusText: 'The comprehensive syllabus for the 2025 non-technical categories has been revised.',
  examDownloadPdf: 'Download PDF',
  prepText: 'Access curated mock tests, previous year papers, and live doubt sessions.',
  examTakeMockTest: 'Take Mock Test',
  examExploreResources: 'Explore Resources',
  examHeaderTitle: 'Exams',

  examNotifications: [
    {
      id: 'ssc-tier-1',
      title: 'SSC CGL 2024 Tier 1 Official Notification',
      org: 'Staff Selection Commission',
      date: 'Oct 24, 2024',
      status: 'NEW',
      stats: '175 Days Left',
      icon: Images.bank,
    },
    {
      id: 'upsc-mains',
      title: 'UPSC Civil Services Main Exam Schedule',
      org: 'Union Public Service Commission',
      date: 'Oct 22, 2024',
      status: 'Closed',
      stats: '12.4k Candidates',
      icon: Images.employee,
    },
    {
      id: 'ibps-po',
      title: 'IBPS PO 2024 Preliminary Exam Result',
      org: 'Institute of Banking Personnel',
      date: 'Oct 21, 2024',
      status: 'NEW',
      stats: 'Admit Card Out',
      icon: Images.exams,
    },
  ],
  
  jobsList: [
    {
      title: 'Frontend Developer',
      company: 'TechSolutions',
      location: 'Bengaluru (Remote)',
      salary: '₹12L - ₹22L PA',
      aiMatch: '95% AI MATCH',
      image: Images.indesign,
    },
    {
      title: 'Marketing Manager',
      company: 'FinBank Global',
      location: 'Mumbai, MH',
      salary: '₹18L - ₹25L PA',
      aiMatch: '91% AI MATCH',
      image: Images.aftereffects,
    },
    {
      title: 'UI/UX Designer',
      company: 'InnovaSoft',
      location: 'Hyderabad (On-site)',
      salary: '₹15L - ₹20L PA',
      aiMatch: '88% AI MATCH',
      image: Images.tiktok,
    },
  ],

  homeJobs: [
    {
      title: 'Senior Systems Architect',
      company: 'Google',
      location: 'Mountain View, CA',
      aiMatch: '98% AI Match',
      tags: ['Full-time', '$180k - $240k'],
      image: Images.indesign,
    },
    {
      title: 'Product Designer (UX)',
      company: 'Spotify',
      location: 'Remote',
      aiMatch: '92% AI Match',
      tags: ['Remote', 'Contract'],
      image: Images.aftereffects,
    },
    {
      title: 'AI Research Scientist',
      company: 'Meta',
      location: 'London',
      aiMatch: '95% AI Match',
      tags: ['On-site', 'Full-time'],
      image: Images.tiktok,
    },
  ],
  homeGovtJobs: [
    { code: 'UPSC', title: 'Civil Services Exam 2024', deadline: '15 Oct' },
    { code: 'SSC', title: 'Combined Graduate Level', deadline: '22 Oct' },
    { code: 'RBI', title: 'Grade B Officers', deadline: '05 Nov' },
  ],
  homePrivateCompanies: [
    { name: 'Microsoft', roles: '12 ROLES', image: Images.microsoft },
    { name: 'Amazon', roles: '45 ROLES', image: Images.amazonpay },
    { name: 'Stripe', roles: '08 ROLES', image: Images.stripe },
    { name: 'Slack', roles: '14 ROLES', image: Images.slack },
  ],
  homeUpcomingExams: [
    {
      id: 'gate',
      date: '24 SEPT, 2024',
      title: 'GATE 2025 Registration',
      desc: 'Graduate Aptitude Test in Engineering regular registration window opens today.',
    },
    {
      id: 'ssc',
      date: '30 SEPT, 2024',
      title: 'SSC CGL Tier-1 Notice',
      desc: 'Official exam city and admit card release update expected this week.',
    },
    {
      id: 'upsc',
      date: '03 OCT, 2024',
      title: 'UPSC Mains Schedule',
      desc: 'Detailed timetable, session timing and paper-wise instructions are available.',
    },
  ],
} as const;
