const ApiUrl = {
  REGISTER: 'auth/register',
  REQUEST_OTP: 'auth/request-otp',
  VERIFY_OTP: 'auth/verify-otp',
  LOGIN: 'auth/login',
  PostAllJobs: 'recruiterJob/allJobs',
  PostJobById: 'recruiterJob/jobById',
  UpdateJob: 'recruiterJob/updateJob',
  DeleteJob: 'recruiterJob/deleteJob',
  similarJobs: 'recruiterJob/similarJobs',
  ApplyJob: 'jobApplication/apply',
  appliedByUser: 'jobApplication/CheckApplyJobsStatus',
  createJob: 'recruiterJob/create',
  myAppliedJobs: 'jobApplication/myApplications',
  authGetProfile: 'auth/get-profile',
  authUpdateProfile: 'auth/update-profile',
  dashboardStats: 'recruiterJob/dashboardStats',
  myJobs: 'recruiterJob/myJobs',
  recruiterApplicants: 'recruiterJob/applicants',
  recruiterApplicantsByJob: 'recruiterJob/applicantsByJob',
  updateApplicationStatus: 'recruiterJob/updateStatus',
  allAppliedApplicants: 'recruiterJob/allAppliedApplicants',
  LATEST_JOBS: 'jobs/latest',
  LATEST_EXAMS: 'exams/latest',
  ALL_SKILLS: 'auth/all-skills',
  userJobMatchProfile: 'recruiterJob/userJobMatchProfile',
  authProfileStrength: 'auth/profile-strength',
  authGoogleLogin: 'auth/google-login',
  applicationTrends: 'recruiterJob/applicationTrends',
  matchAiApi: 'recruiterJob/matchAiApi',
  saveJob: 'auth/save-job',
  getSavedJobs: 'auth/get-saved-jobs',
  withdrawJob: 'jobApplication/withdraw',
};

export default ApiUrl;