import { StyleSheet } from 'react-native';
import Colors from '../../../../comman/Colors';
import FontsSize from '../../../../comman/Sizes/FontsSize';
import fonts from '../../../../comman/fonts';
import MarginHW from '../../../../comman/Sizes/MarginHW';

export const styles = StyleSheet.create({
  container: { backgroundColor: Colors.screenGray, flex: 1, paddingHorizontal: MarginHW.PaddingW16 },
  content: { paddingTop: 8, paddingBottom: MarginHW.MarginH60 },
  searchRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginBottom: MarginHW.MarginH10 },
  searchBox: { backgroundColor: Colors.white, borderRadius: 10, flex: 1, paddingHorizontal: MarginHW.PaddingW10, paddingVertical: MarginHW.PaddingH3 },
  searchText: { height: 40, color: '#8B93A1', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size14 },
  findButton: { alignItems: 'center', backgroundColor: Colors.ctaBlue, borderRadius: 10, justifyContent: 'center', paddingHorizontal: MarginHW.PaddingW12, paddingVertical: MarginHW.PaddingH10 },
  findButtonText: { color: Colors.white, fontFamily: fonts.LexendBold, fontSize: FontsSize.size10 },
  highlightCard: { backgroundColor: Colors.primaryBlue, borderRadius: 14, padding: 12 },
  highlightTitle: { color: Colors.white, fontFamily: fonts.LexendBold, fontSize: FontsSize.size18, lineHeight: 24 },
  highlightBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 999, marginBottom: MarginHW.MarginH8, paddingHorizontal: MarginHW.PaddingW8, paddingVertical: MarginHW.PaddingH3 },
  highlightMatchesBadge: { alignSelf: 'flex-start', backgroundColor: '#fff', borderRadius: 999, marginBottom: MarginHW.MarginH8, paddingHorizontal: MarginHW.PaddingW8, paddingVertical: MarginHW.PaddingH5, marginTop: MarginHW.MarginH8 },
  highlightBadgeText: { color: Colors.white, fontFamily: fonts.Lexend_SemiBold, fontSize: FontsSize.size10 },
  highlightMatchesBadgeText: { color: Colors.black, fontFamily: fonts.Lexend_SemiBold, fontSize: FontsSize.size10 },
  quickTilesWrap: { gap: MarginHW.MarginW8, marginTop: MarginHW.MarginH10 },
  quickTile: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: MarginHW.PaddingW12, paddingVertical: MarginHW.PaddingH16 },
  quickTileLabel: { color: '#798293', fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size10, letterSpacing: 1 },
  quickTileTitle: { color: Colors.titleInk, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size16, marginTop: MarginHW.MarginH2 },
  quickTileIcon: { alignItems: 'center', backgroundColor: Colors.badgeBlueTint, borderRadius: 10, height: 40, justifyContent: 'center', width: 40 },
  quickTileIconText: { fontSize: FontsSize.size16, color: Colors.brandBlue },
  section: { marginTop: MarginHW.MarginH16 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: MarginHW.MarginH8 },
  sectionTitleWrap: { flex: 1 },
  bankimage: { height: 22, width: 22, },
  sectionTitle: { color: Colors.titleInk, fontFamily: fonts.LexendBold, fontSize: FontsSize.size18 },
  sectionSubTitle: { color: '#6E7685', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size12, marginTop: MarginHW.MarginH2 },
  sectionAction: { color: Colors.brandBlue, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size12 },
  jobCard: { backgroundColor: Colors.white, borderRadius: 14, marginBottom: MarginHW.MarginH12, padding: MarginHW.PaddingW12 },
  jobTopRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: MarginHW.MarginH10 },
  jobCompanyLogo: { backgroundColor: Colors.white, borderWidth: 1, borderColor: '#E4E7EB', borderRadius: 2, height: 50, width: 50 },
  aiBadge: { backgroundColor: '#F2F6FF', borderRadius: 999, paddingHorizontal: MarginHW.PaddingW8, paddingVertical: MarginHW.PaddingH3 },
  aiBadgeText: { color: Colors.brandBlue, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size10 },
  jobTitle: { color: Colors.titleInk, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size22 },
  jobMeta: { color: '#6E7685', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size12, marginTop: MarginHW.MarginH4 },
  jobTagsRow: { flexDirection: 'row', gap: MarginHW.MarginW8, marginTop: MarginHW.MarginH10 },
  jobTag: { backgroundColor: Colors.screenGray, borderRadius: 4, paddingHorizontal: MarginHW.PaddingW8, paddingVertical: MarginHW.PaddingH3 },
  jobTagText: { color: '#6E7685', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size10 },
  quickApply: { alignItems: 'center', backgroundColor: '#ECEDEF', borderRadius: 8, marginTop: MarginHW.MarginH12, paddingVertical: MarginHW.PaddingH8 },
  quickApplyText: { color: '#1C3061', fontFamily: fonts.Lexend_SemiBold, fontSize: FontsSize.size12 },
  govtCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: 10, flexDirection: 'row', gap: MarginHW.MarginW10, marginBottom: MarginHW.MarginH8, paddingVertical: MarginHW.PaddingH14, paddingHorizontal: MarginHW.PaddingW14 },
  govtCodeWrap: { alignItems: 'center', backgroundColor: Colors.screenGray, borderRadius: 8, justifyContent: 'center', height: 45, width: 45 },
  govtCode: { color: Colors.brandBlue, fontFamily: fonts.LexendBold, fontSize: FontsSize.size10 },
  govtCenter: { flex: 1 },
  govtTitle: { color: Colors.titleInk, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size16 },
  govtMeta: { color: '#6E7685', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size10, marginTop: MarginHW.MarginH2 },
  deadlineLabel: { color: '#AD4B4B', fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size10, textAlign: 'right' },
  deadlineDate: { color: Colors.titleInk, fontFamily: fonts.LexendBold, fontSize: FontsSize.size12, textAlign: 'right' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: MarginHW.MarginW8 },
  chip: { alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.white, borderRadius: 14, paddingVertical: MarginHW.PaddingH12, width: '48%' },
  chipIcon: { height: 40, width: 40 },
  chipText: { color: Colors.textCharcoal, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size16, marginTop: MarginHW.MarginH2 },
  companyRoles: { color: '#8B93A1', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size10, marginTop: MarginHW.MarginH2 },
  upcomingList: { gap: MarginHW.MarginW10, paddingRight: MarginHW.PaddingW5 },
  upcomingCard: { backgroundColor: Colors.white, borderRadius: 10, padding: MarginHW.PaddingW10, width: 285 },
  upcomingDate: { color: Colors.brandBlue, fontFamily: fonts.Lexend_Medium, fontSize: FontsSize.size10 },
  upcomingTitle: { color: Colors.titleInk, fontFamily: fonts.LexendBold, fontSize: FontsSize.size14, marginBottom: MarginHW.MarginH4 },
  upcomingDesc: { color: '#6E7685', fontFamily: fonts.Lexend_Regular, fontSize: FontsSize.size10, marginBottom: MarginHW.MarginH8 },
});
